#!/usr/bin/env node
var argv = require('minimist')(process.argv.slice(2))
, _ = require('lodash')
, app = new require('./core/app')

if (!argv._[0] || argv._[0] === 'server') {
  require('./core/server')
} else 
if (argv._[0] === 'convert') {
  var config = {source: argv._[1], target: argv._[2]}
  var source = new app.modules[argv.source].provider(config)
  var target = new app.modules[argv.target].provider(config)
  var data = source.read()
  target.write(data)
}
