#!/usr/bin/env node
var argv = require('minimist')(process.argv.slice(2))
, _ = require('lodash')
, app = new require('./core/app')

if (!argv._[0] || argv._[0] === 'server') {
  require('./core/server')
} else 
//./graphiy convert path-to-source path-to-target --source="provider-name" --target="provider-name"
var defaults = {root: 'root'}

//TODO where to put 'convert' configs?
_.extend(defaults, {
  ignore: ['index']
, noTextParsing: true
})

if (argv._[0] === 'convert') {
  var config = _.defaults({source: argv._[1], target: argv._[2]}, defaults)
  var source = new app.modules[argv.source].provider(config)
  var target = new app.modules[argv.target].provider(config)
  var items = source.read()
  target.write(items)
}
//./graphiy render path-to-repo --view="view_name"
if (argv._[0] === 'render') {
  var config = app.getRepoConfig(argv._[1], {render: argv.view})
  var provider = new app.modules[config['repository.type']].provider(config)
  var view = new app.modules[config['repository.type']].view(config)
  var items = provider.read()
  var data = view.render(items)
  provider.write(data)
}
